import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";

const inter_Tight = Inter_Tight({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-interTight",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter_Tight.variable} font-sans`}>{children}</body>
    </html>
  );
}
